name: Container
on: push

# jobs:
#   node-docker:
#     runs-on: ubuntu-latest
#     container: 
#       image: node:18-alpine3.15
#     steps:
#       - name: Log Node version
#         run: |
#           node -v
#           cat /etc/os-release

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: arpanknandi/node-api:latest
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
      
    steps:
      - name: Post a user
        run: "curl -X POST http://host.docker.internal:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"Patu\", \"address\": \"Motu\"}'"

      - name: Get Users
        run: curl http://host.docker.internal:3001/api/users