name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
      # fail-fast means that if one of the jobs fail then others will not be executed, fail-fast false means that other jobs will run independently
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      
      - uses: actions/setup-node@v1
        with:
          # node-version: 6
          node-version: ${{ matrix.node-version }}

      - name: Log node version
        run: node -v
